/* ModeloLogico: */

CREATE DATABASE tcc CHARACTER SET utf8 COLLATE utf8_bin;

USE tcc;

CREATE TABLE RESUMOS (
    RES_ID INT(3) PRIMARY KEY,
    RES_TITULO VARCHAR(100),
    RES_RESUMO TEXT UNIQUE
);

CREATE TABLE OBJETIVO (
    OBJ_ID INT(3) PRIMARY KEY,
    OBJ_CONSTRUCOES_LINGUISTICAS VARCHAR(500),
    OBJ_CATEGORIA VARCHAR(3),
    OBJ_JUSTIFICATIVA VARCHAR(100),
    FK_RESUMOS_RES_ID INT(3)
);

CREATE TABLE CONCLUSAO (
    CON_ID INT(3) PRIMARY KEY,
    CON_CONSTRUCOES_LINGUISTICAS VARCHAR(500),
    CON_CATEGORIA VARCHAR(7),
    CON_JUSTIFICATIVA VARCHAR(100),
    FK_RESUMOS_RES_ID INT(3)
);
 
ALTER TABLE OBJETIVO ADD CONSTRAINT FK_OBJETIVO_2
    FOREIGN KEY (FK_RESUMOS_RES_ID)
    REFERENCES RESUMOS (RES_ID)
    ON DELETE SET NULL;
 
ALTER TABLE CONCLUSAO ADD CONSTRAINT FK_CONCLUSAO_2
    FOREIGN KEY (FK_RESUMOS_RES_ID)
    REFERENCES RESUMOS (RES_ID)
    ON DELETE SET NULL;