START TRANSACTION;

SET NAMES utf8mb4;
SET CHARACTER SET utf8mb4;

SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS CONCLUSAO;
DROP TABLE IF EXISTS OBJETIVO;
DROP TABLE IF EXISTS RESUMOS;

CREATE TABLE RESUMOS (
    RES_ID INT PRIMARY KEY,
    RES_TITULO VARCHAR(500),
    RES_RESUMO TEXT
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE OBJETIVO (
    OBJ_ID INT PRIMARY KEY,
    OBJ_CONSTRUCOES_LINGUISTICAS VARCHAR(1000),
    OBJ_CATEGORIA VARCHAR(3),
    OBJ_JUSTIFICATIVA VARCHAR(100),
    FK_RESUMOS_RES_ID INT,
    INDEX idx_fk_resumos (FK_RESUMOS_RES_ID)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE CONCLUSAO (
    CON_ID INT PRIMARY KEY,
    CON_CONSTRUCOES_LINGUISTICAS VARCHAR(1000),
    CON_CATEGORIA VARCHAR(7),
    CON_JUSTIFICATIVA VARCHAR(100),
    FK_RESUMOS_RES_ID INT,
    INDEX idx_fk_resumos (FK_RESUMOS_RES_ID)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

ALTER TABLE OBJETIVO ADD CONSTRAINT FK_OBJETIVO_2
    FOREIGN KEY (FK_RESUMOS_RES_ID)
    REFERENCES RESUMOS (RES_ID)
    ON DELETE SET NULL
    ON UPDATE CASCADE;

ALTER TABLE CONCLUSAO ADD CONSTRAINT FK_CONCLUSAO_2
    FOREIGN KEY (FK_RESUMOS_RES_ID)
    REFERENCES RESUMOS (RES_ID)
    ON DELETE SET NULL
    ON UPDATE CASCADE;

SET FOREIGN_KEY_CHECKS = 1;

COMMIT;

CREATE INDEX idx_resumos_titulo ON RESUMOS(RES_TITULO);
CREATE INDEX idx_objetivo_categoria ON OBJETIVO(OBJ_CATEGORIA);
CREATE INDEX idx_conclusao_categoria ON CONCLUSAO(CON_CATEGORIA);


-- Verificações pra ver se tá tudo OK.
SELECT 'Setup do schema concluído com sucesso!' as Status;
SELECT COUNT(*) as Total_Resumos FROM RESUMOS;
SELECT COUNT(*) as Total_Objetivos FROM OBJETIVO;
SELECT COUNT(*) as Total_Conclusoes FROM CONCLUSAO;

SELECT TABLE_NAME, TABLE_COLLATION 
FROM INFORMATION_SCHEMA.TABLES 
WHERE TABLE_SCHEMA = DATABASE() 
AND TABLE_NAME IN ('RESUMOS', 'OBJETIVO', 'CONCLUSAO');